steps:
# Build testing web app
- name: 'gcr.io/cloud-builders/npm:node-12.18.3'
  args: [ 'install' ]
  dir: 'mobile-app/app'
  
# Install node packages
- name: 'gcr.io/cloud-builders/npm:node-12.18.3'
  args: [ 'install' ]
  dir: 'mobile-app/'
  
  # Build testing web app
- name: 'gcr.io/cloud-builders/npm:node-12.18.3'
  args: [ 'run', 'build:prod']
  dir: 'mobile-app/app'

  
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "--version", "current"]
  dir: 'mobile-app/'
timeout: "1600s"
