steps:
# Load Dockerfile
#- name: gcr.io/cloud-builders/gsutil
#  args: ['cp', 'gs://$_BUCKET/microservices/invoice/staging.dockerfile', 'Dockerfile']
#  dir: microservices/invoice/

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/stefano-lab/stoned-api', '.']
  dir: microservices/api/

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/stefano-lab/stoned-api']
  dir: microservices/api/

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'stoned-api', '--image', 'gcr.io/beyondborders/stoned-api', '--region', 'europe-west2', '--platform', 'managed', '--timeout', '899']

images:
- gcr.io/beyondborders/stoned-api
